AArnott/Library.Template

azure-pipelines/dotnet.yml
src/Library.Tests/CalculatorTests.cs
src/Library.Tests/Library.Tests.csproj

Microsoft's long-term support for .NET Core 1.x and 2.0 [are over][LTS]. Customers targeting these versions are in a really bad place due to no security patches being offered and thus there are likely few to none out there.
[LTS]: https://github.com/dotnet/core/blob/e2f22a7106860c0e5dc98bb36dc648a779944ad5/microsoft-support.md#net-core-releases

Drop .NET Core 2.0 targeting in test project

---

nuget.config

This ensures that restore always uses the sources in nuget.config rather than a cache that happens to be on the local box. It helps avoid bugs that are not caught till a build suddenly fails on some machine somewhere because it didn't happen to have a package cached locally from some other source.
It also mitigates the risk on private build agents that a package cache is "poisoned" by some build already done on that agent with other package sources where the id/version of a package collides but the contents are not actually identical.

Use a local package cache

---

azure-pipelines/Get-TempToolsPath.ps1
azure-pipelines/Get-nbgv.ps1

AGENT_TOOLSDIRECTORY may not be cleaned between each build, so AGENT_TEMPDIRECTORY which certainly is cleaned is a better place to put files that might need newer versions downloaded and/or installed each time.

Use AGENT_TEMPDIRECTORY for tools

---

azure-pipelines/install-dependencies.yml
init.ps1
tools/Install-NuGetCredProvider.ps1

On private agents where it may exist from a prior build, it's important that we update it to whatever the latest version is.

Upgrade NuGet credprovider in Azure Pipelines

---

src/Directory.Build.props

Although we already pin the SDK which includes compilers, when we use msbuild.exe (including VS) to build we still get whatever compilers are on the box. Pinning the compilers has many of the same merits as pinning the SDK.

Pin the compiler version

---

azure-pipelines/dotnet.yml

A suggestion to use Agent.JobName variable for symbols folder name to be consistent and to avoid potential bugs when adapting the template with a different job name.

Use agent jobname for for symbols folder

---

.github/workflows/Linux.runsettings
.github/workflows/Windows.runsettings
.github/workflows/build.yml
.github/workflows/macOS.runsettings
azure-pipelines/Darwin.runsettings
azure-pipelines/Linux.runsettings
azure-pipelines/Windows_NT.runsettings
azure-pipelines/artifacts/testResults.ps1
azure-pipelines/dotnet.yml
azure-pipelines/install-dependencies.yml

This makes diagnosing test runner crashes and hangs on Azure Pipelines and GitHub Actions possible.
After such a failure, a testResults artifact is collected that includes the `Sequence_*.xml` and `testhost.*.dmp` files collected at the timeout or crash.
These files can then be downloaded from the CI/PR artifacts for study.
Dumps are only collected on Windows agents. Collecting dumps on other OS's is not supported by the test runner.

Collect dumps and sequence.xml files on test hangs and crashes

---

.github/workflows/build.yml
azure-pipelines/Get-ProcDump.ps1
azure-pipelines/Set-EnvVars.ps1
azure-pipelines/install-dependencies.yml
init.ps1

Just using nuget instead of choco makes it take less than 1 second instead of nearly a minute.
It also removes the requirement for chocolatey to be installed on AzP agents, which helps compatibility with custom/private agents.
Also move it to init.ps1 so it doesn't require a special AzP or GitHub Actions task and it canl run on local dev boxes.

Acquire procdump via nuget

---

azure-pipelines.yml
azure-pipelines/build.yml
azure-pipelines/microbuild.before.yml
azure-pipelines/official.yml
azure-pipelines/variables/SignType.ps1
azure-pipelines/variables/ci_feed.ps1

This presents this beautiful UI in Azure Pipelines when queuing:

Use SignType parameter instead of variable

---

global.json
init.ps1
tools/Install-DotNetSdk.ps1

When installing the .NET SDK or runtime, if the installer wants a system restart, it would do so quietly. This avoids the restart but adds a prompt at the end of the script to inform the user of a restart being required when necessary.
Fixes #57

Avoid unannounced system restart

---

azure-pipelines/Get-SymbolFiles.ps1
azure-pipelines/artifacts/test_symbols.ps1
azure-pipelines/dotnet.yml

When investigating test run failures from Azure Pipelines, symbols from test binaries may be just as important as symbols from product binaries. So publish them as pipeline artifacts as well.
Also index all these symbols even in PR builds, since PR builds may fail and investigations may be required.

Publish test symbols on failures

---

azure-pipelines.yml
azure-pipelines/build.yml
azure-pipelines/publish-codecoverage.yml

A means to 'opt in' to building on macOS remains. And for repos where macOS agents are important to keep in, it's easy to remove the parameter and/or change its default from off to on.

Remove macOS from Azure Pipeline runs

---

.editorconfig

Remove the second [*.cs] because it is already declared at line 122

Remove [*.cs]

---

tools/Install-DotNetSdk.ps1

Workaround for https://github.com/dotnet/install-scripts/issues/136
By pinning the version of the script, any future regressions would be caught only when we explicitly upgrade the pinned version, making it obvious what the problem is, and should help us be rock-stable otherwise.

Notice .NET SDK install failure earlier and workaround broken script

---

Directory.Build.props

This ensures that if you build a dll and copy it somewhere, then build again, you haven't lost the ability to debug the original dll because it carries the pdb with it wherever it goes.
We do *not* embed the pdb in the official builds however because the official builds will archive the pdb so it isn't lost, and it would unnecessarily bloat the assembly.

Embed PDBs for all local builds

---

tools/Install-DotNetSdk.ps1

As reported in https://github.com/neuecc/MessagePack-CSharp/issues/1244

Fixes the Install-DotNetSdk.ps1 script when the path to the repo contains spaces

---

tools/Install-DotNetSdk.ps1

Add support for TargetFrameworks of the form netXX to the Dotnet SDK installer script.  I'm working on a project where I want tests to support the net5 and net6 target frameworks.  When I set global.json to net6, the runtimes for the test projects fail to pick up net5.  This fix adds support for detecting target framework runtimes of the form netXX.

Add support for TargetFrameworks of the form netXX

---

azure-pipelines/microbuild.after.yml

It actually does something useful, and will soon be mandated.

Enable Component Governance to PR builds

---

tools/Install-DotNetSdk.ps1

The `$env:PROCESSOR_ARCHITECTURE` environment variable simply isn't set on linux.

Fix ARM detection on Linux

---

Directory.Build.props

Not that this template repo itself requires it, but it's a great baseline to start with as it means the repo will grow nicely as it gets more complicated for real projects.

Activate msbuild 17's platform negotiation feature

---

Directory.Build.props

If this builds, I guess we don't need it any more. The SDK is supposed to implicitly reference it, but we added it back when there were certain TFMs or SDK version that didn't actually do it.

Remove explicit Microsoft.NETFramework.ReferenceAssemblies PackageReference

---

test/Library.Tests/Library.Tests.csproj

.NET 5 falls out of Microsoft support in just a few days, so folks should focus testing on the currently supported platforms.

Test on .NET 6 instead of .NET 5

---

azure-pipelines/dotnet-test-cloud.ps1
tools/Install-DotNetSdk.ps1

Activating this within a repo might look like this:
In init.ps1, make this modification:
```diff
-    & "$PSScriptRoot\tools\Install-DotNetSdk.ps1" -InstallLocality $InstallLocality
+    & "$PSScriptRoot\tools\Install-DotNetSdk.ps1" -InstallLocality $InstallLocality -IncludeX86
```
Then in dotnet.yml, make this modification:
```diff
- powershell: azure-pipelines/dotnet-test-cloud.ps1 -Configuration $(BuildConfiguration) -Agent $(Agent.JobName) -PublishResults
-  displayName: dotnet test
+  displayName: dotnet test x64
+
+- powershell: azure-pipelines/dotnet-test-cloud.ps1 -Configuration $(BuildConfiguration) -Agent $(Agent.JobName) -x86 -PublishResults
+  displayName: dotnet test x86
+  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
```

Add support for running 32-bit tests

---

azure-pipelines/artifacts/_all.ps1
azure-pipelines/artifacts/_pipelines.ps1
azure-pipelines/artifacts/_stage_all.ps1

Now if a repo needs to post-process the staged artifacts before they are published, it need only add these lines to the pipeline to do just the stage:
```yaml
- powershell: azure-pipelines/artifacts/_pipelines.ps1 -ArtifactNameSuffix "-$(Agent.JobName)" -StageOnly
failOnStderr: true
displayName: Stage artifacts
condition: succeededOrFailed()
```
Note the `-StageOnly` switch. 
The subsequent task without that switch will skip staging artifacts that were already staged, and proceed with publish.

Add ability to split stage and publish artifact steps

---

azure-pipelines/artifacts/coverageResults.ps1

The test runner is creating *two* cobertura.xml files for each test run. Besides doubling the size of the coverageResults artifact, this makes the `publish-codecoverage.yml` pipeline step do much more work which can take *minutes* instead of seconds.

Include only unique coverage reports in artifact

---

.github/workflows/build.yml
azure-pipelines/Get-CodeCovTool.ps1
azure-pipelines/dotnet.yml
azure-pipelines/publish-CodeCov.ps1

Replaces the bash CodeCov uploader with the latest binary version.  A PowerShell script downloads the latest codecov binary.  Another PowerShell script collects and uploads code coverage artifact files to CodeCov.io.  You can pass flags and a coverage report name as parameters.

CodeCov binary uploader

---

.devcontainer/Dockerfile
Directory.Build.targets
global.json
src/Library/Library.csproj
test/Library.Tests/CalculatorTests.cs
test/Library.Tests/Library.Tests.csproj

[.NET Core 3.1 is dead](https://dotnet.microsoft.com/en-us/download/dotnet). Long live .NET 6 and 7.

Drop .NET Core 3.1 target

---

azure-pipelines/Get-NuGetTool.ps1

As per NuGet.org, the NuGet.exe version used currently has at least one vulnerability https://www.nuget.org/packages/NuGet.CommandLine/5.2.1. Hence proposing to use latest NuGet.exe version always. If the latest version has a regression, we can always pin to a particular version by passing `v{versionnumber}` as a parameter to the powershell script.

Use latest NuGet.exe version

---

azure-pipelines/microbuild.before.yml

NOTICE generation fails frequently due to throttling, so this will both help keep PRs going, and reduce the demand on the network resource.

Skip NOTICE generation on PRs

---

nuget.config

We don't need it now that we're using stable Microsoft.CodeCoverage package versions.

Drop test-tools as a nuget feed source

---

Directory.Packages.props
test/Library.Tests/Library.Tests.csproj

It's brought in via Microsoft.NET.Test.Sdk anyway.

Drop Microsoft.CodeCoverage reference

---

.config/dotnet-tools.json
.github/dependabot.yml

It's part of the SDK now, and the version on nuget.org is no longer maintained.

Remove `dotnet-format` as a tool

---

azure-pipelines/OptProf.yml
azure-pipelines/build.yml
azure-pipelines/official.yml

This regroups and documents the pipeline parameters in `official.yml` and `build.yml` so folks in consuming repos know what's safe to change and what isn't.

Document pipeline parameters

---

azure-pipelines/apiscan.yml

This will make it so that API Scan logs are not dropped when any of the API Scan checks fail.
Some of these failures need the logs in order to be troubleshooted.

Always include apiscan logs

---

Directory.Packages.props

- Bump xunit from 2.8.0 to 2.8.1
- Bump Microsoft.NET.Test.Sdk from 17.9.0 to 17.10.0
- Bump xunit.runner.visualstudio from 2.8.0 to 2.8.1

Merge test related dependency updates

---

azure-pipelines/vs-insertion.yml
azure-pipelines/vs-validation.yml

Enabling shallow cloning will make cloning the VS repo faster when creating the PR.
This is available because of this change: https://devdiv.visualstudio.com/Engineering/_git/MicroBuild/pullrequest/554184

Enable ShallowClone when performing insertion

---

Expand-Template.ps1

Windows PowerShell 5.1 uses Default encoding for Get-Content instead of UTF-8 which incorrectly reads the encoding of some yaml files and breaks their emojis (like 📢) when running expand-template.ps1.

Ensure Expand-Template uses UTF-8 when replacing placeholders.

---

test/Library.Tests/Library.Tests.csproj

The mono runtime is obsolete for most applications.

Avoid running tests on mono for test project

---

Directory.Packages.props
azure-pipelines/dotnet-test-cloud.ps1
test/Directory.Build.props

This reverts commit 01eeb1aff44be490aea525baa92f89240ba2f682, reversing changes made to 0a42cd9afd1e40f6a5392850a5115ca5f42dfd9a.
See https://github.com/Tyrrrz/GitHubActionsTestLogger/discussions/37 for an ongoing discussion. The short explanation is that this new logger is simply too likely to break things. It was hard enough to get it to work in the template repo itself, but the very first "real" repo I merged the change into broke with a crash in the test runner on Windows.

Revert "Merge pull request #319 from AArnott/betterTestingLibTemplate"

---

.github/actions/publish-artifacts/action.yaml
tools/artifacts/testResults.ps1

They are intended to be collected as part of the `testResults` artifact.

Fix test logs collection

---

Expand-Template.ps1
azure-pipelines/apiscan.yml
azure-pipelines/build.yml
azure-pipelines/unofficial.yml
azure-pipelines/vs-validation.yml

Separate official and unofficial pipelines.
This is to satisfy the requirement that pipelines marked as production never use the unofficial templates.

Separate official and unofficial pipelines

---

Directory.Build.props
Directory.Build.targets
azure-pipelines/NuGetSbom.props
azure-pipelines/NuGetSbom.targets

Reverts AArnott/Library.Template#362
The new SBOM v2 plugin breaks on `dotnet build` due to its use of the `Unzip` task, which inside a project with the VSSDK.BuildTools is overridden to one that targets .NET and is incompatible with .NET Framework.

Revert "Opt in to the new MicroBuild SBOM behavior"

---

azure-pipelines/microbuild.before.yml

Component Detection that was being injected was happening too late (way after NOTICE task was running) which was causing the generate NOTICE task to fail.
Fixes #389

Run Component Detection explicitly before Notice

---

azure-pipelines/build.yml
azure-pipelines/dotnet.yml

Pass through `System.AccessToken` when real signing on non-Windows builds
Production signing on non-Windows machines requires the `System.AccessToken` to properly acquire the token needed to sign files.
- Add a new parameter to `dotnet.yml` to pass the `System.AccessToken` through the environment variables of the `dotnet` script
- Pass through the parameter to set `System.AccessToken` for Linux and MacOS builds when real signing
- Verified a Linux build can now real sign

Pass through System.AccessToken when real signing on non-Windows builds
