azure-pipelines/dotnet.yml
=> Fix test run names

azure-pipelines/dotnet.yml
=> Merge code coverage from all test runs and agents

Expand-Template.ps1, azure-pipelines/expand-template.yml
=> Add -Squash switch to Expand-Template.ps1

.vscode/extensions.json
@AArnott, is this file created manually or is it from some tool? If from a tool, do you know where this file originally came from? If so, I'd like to send a PR to the original location to fix for all future users.
=> Use HTTPS URLs wherever possible

Expand-Template.cmd, Expand-Template.ps1, init.cmd
=> Add Expand-Template.cmd stub

src/Directory.Build.props, src/Library.Tests/Library.Tests.csproj
Also stop packing pdb in main nupkg
=> Update package refs

.github/workflows/build.yml, Expand-Template.ps1, README.md, azure-pipelines.yml, azure-pipelines/Set-EnvVars.ps1, azure-pipelines/artifacts/Variables.ps1, azure-pipelines/artifacts/_pipelines.ps1, azure-pipelines/artifacts/_stage_all.ps1, azure-pipelines/build.yml, azure-pipelines/variables/_pipelines.ps1, tools/Install-DotNetSdk.ps1
=> Start with GitHub Actions

.github/workflows/build.yml, Expand-Template.ps1, Library.sln, azure-pipelines/dotnet.yml, azure-pipelines/expand-template.yml, init.ps1
=> Move sln file to repo root

.github/workflows/build.yml, azure-pipelines/install-dependencies.yml
=> Add -y switch to choco install

azure-pipelines/install-dependencies.yml
=> Bring back access tokens for AzP feed access

Directory.Build.props, azure-pipelines/artifacts/_stage_all.ps1, global.json, test/Library.Tests/Library.Tests.csproj
=> Update package references and SDK

Directory.Build.props, Directory.Build.targets, src/Directory.Build.targets
Get WPF inner-builds to import NuGet packages' imports
=> Get WPF inner-builds to import NuGet packages' imports

azure-pipelines/variables/_pipelines.ps1, tools/Set-EnvVars.ps1
=> Adapt to GitHub's new env and path operations

.editorconfig, Directory.Build.props, azure-pipelines/dotnet.yml, global.json, test/.editorconfig, test/Directory.Build.props
=> Update to .NET 5.0.102 SDK, add net5.0 targets

tools/Install-DotNetSdk.ps1
This may help with curl failures, as described in https://github.com/dotnet/install-scripts/issues/139
=> Update .NET installer script

azure-pipelines/install-dependencies.yml, init.ps1
This works around microsoft/artifacts-credprovider#244
=> Use NuGetAuthenticate in AzP instead of hand installation

azure-pipelines/dotnet.yml, test/Directory.Build.props
It is no longer in its LTS lifecycle.
=> Drop netcoreapp2.1 as a target

.github/workflows/build.yml, azure-pipelines/Convert-PDB.ps1, azure-pipelines/Get-SymbolFiles.ps1, azure-pipelines/artifacts/symbols.ps1
Brings the GitHub workflows more in sync with Azure Pipelines.
=> GitHub workflows update

Directory.Build.props, global.json, src/Library/Calculator.cs, src/Library/Library.csproj
Also:
1. Use C# 10 syntax.
2. Embed the repo README.md file in the built nuget package.
=> Update to the .NET 6 SDK

azure-pipelines/Get-ArtifactsStagingDirectory.ps1, azure-pipelines/artifacts/Variables.ps1, azure-pipelines/artifacts/_stage_all.ps1, azure-pipelines/dotnet-test-cloud.ps1
=> Simplify Join-Path expressions

azure-pipelines/dotnet-test-cloud.ps1
If this works, it resolves https://github.com/microsoft/vstest/issues/3532.
=> Increase test timeout to 60s

tools/Install-DotNetSdk.ps1
* Stop popping Windows Explorer dialogs
* Stop installing the same .NET runtime versions multiple times.
* Install WindowsDesktop too.
=> Fix several Install-DotNetSdk issues

azure-pipelines/Merge-CodeCoverage.ps1
=> Fix perf scaling issue in merging coverage reports

Directory.Packages.props, azure-pipelines/test.runsettings, nuget.config, test/Library.Tests/Library.Tests.csproj
=> Switch to code coverage preview with static analysis

tools/Install-DotNetSdk.ps1
This enables downloading newer SDK versions.
=> Update the dotnet-install.ps1 script

.github/workflows/build.yml, azure-pipelines/build.yml
#293 broke it and somehow went uncaught.
=> Fix linux build agent on AzDO

Expand-Template.ps1, azure-pipelines/Get-CodeCovTool.ps1, azure-pipelines/Merge-CodeCoverage.ps1, azure-pipelines/artifacts/Variables.ps1, azure-pipelines/artifacts/_pipelines.ps1, azure-pipelines/artifacts/_stage_all.ps1, azure-pipelines/artifacts/coverageResults.ps1, azure-pipelines/dotnet-test-cloud.ps1, azure-pipelines/publish-CodeCov.ps1, azure-pipelines/variables/DotNetSdkVersion.ps1, azure-pipelines/variables/_pipelines.ps1, tools/Install-DotNetSdk.ps1, tools/Install-NuGetCredProvider.ps1, tools/Set-EnvVars.ps1
=> Use `-LiteralPath` instead of `-Path` in ps1 scripts

Expand-Template.ps1, tools/variables/InsertJsonValues.ps1
I believe that `LibraryName` here is a typo considering that it is in a loop and we couldn't just replace it with a fixed string (even one that is specific to the repo)
=> Fix InsertJsonValues script

azure-pipelines/build.yml, azure-pipelines/official.yml, azure-pipelines/unofficial.yml, azure-pipelines/vs-insertion.yml
- [Disable redundant 1ES SBOM task](https://github.com/AArnott/Library.Template/commit/65f844095c1638f14f4bc8c37f29534f6ca326a3)
- [Consolidate SDL tasks for insertion job](https://github.com/AArnott/Library.Template/commit/6ed2f360da0cf53546b2ea4d11330958bd7883be)
- [Put publishing code coverage under a switch](https://github.com/AArnott/Library.Template/commit/039ac0b644f5cc3cab1982542457e2d7e0a2e607)
=> Pipeline optimizations

azure-pipelines/prepare-insertion-stages.yml
Updated MicroBuildArchiveSymbols task version and added Azure subscription and environment variables.
=> Migrate from managed identity to service connection for symbol archiving
